apiVersion: v1
kind: Pod
metadata:
  labels:
    run: cowweb
  name: cowweb
spec:
  containers:
  - image: phx.ocir.io/orasejapan/cn_study_repo/helidon-mp:0.0.1
    name: cowweb
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
